SELECT A.CONTEST_ID, A.HACKER_ID, A.NAME,
    SUM(S.TS) AS TS,
    SUM(S.TAS) AS TAS,
    SUM(V.TV) AS TV,
    SUM(V.TUV) AS TUV

FROM CONTESTS AS A

JOIN COLLEGES AS B
    ON A.CONTEST_ID=B.CONTEST_ID

JOIN CHALLENGES AS C
    ON B.COLLEGE_ID=C.COLLEGE_ID

LEFT JOIN
    (SELECT CHALLENGE_ID, SUM(TOTAL_SUBMISSIONS) AS TS, SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TAS
     FROM SUBMISSION_STATS GROUP BY CHALLENGE_ID) AS S
     ON C.CHALLENGE_ID=S.CHALLENGE_ID

LEFT JOIN
    (SELECT CHALLENGE_ID, SUM(TOTAL_VIEWS) AS TV, SUM(TOTAL_UNIQUE_VIEWS) AS TUV
     FROM VIEW_STATS GROUP BY CHALLENGE_ID) AS V
     ON C.CHALLENGE_ID=V.CHALLENGE_ID

GROUP BY A.CONTEST_ID, A.HACKER_ID, A.NAME

HAVING (TS+TAS+TV+TUV) > 0

ORDER BY A.CONTEST_ID, A.HACKER_ID, A.NAME;